---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: locust
  name: locust
spec:
  replicas: 1
  selector:
    matchLabels:
      app: locust
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: locust
    spec:
      containers:
        - image: locustio/locust
          name: locust
          ports:
            - name: default
              containerPort: 8089
---
apiVersion: v1
kind: Service
metadata:
  namespace: monitoring
  name: prometheus
spec:
  type: ClusterIP
  selector:
    app: locust
  ports:
    - port: 8089
      targetPort: default
---
apiVersion: v1
kind: Service
metadata:
  namespace: monitoring
  name: prometheus
spec:
  type: NodePort
  selector:
    app: locust
  ports:
    - port: 8089
      targetPort: default
      nodePort: 10000
