---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: elk
  name: logstash
  labels:
    app: logstash
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logstash
  template:
    metadata:
      labels:
        app: logstash
    spec:
      containers:
        - name: logstash
          image: docker.elastic.co/logstash/logstash:7.9.0
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: "1000Mi"
              cpu: "2000m"
            requests:
              memory: "500Mi"
              cpu: "1000m"
          ports:
            - name: default
              containerPort: 9600
            - name: tcp
              containerPort: 5000
            - name: beats
              containerPort: 5044
          volumeMounts:
            - name: config-volume
              mountPath: /usr/share/logstash/config
            - name: config-pipeline-volume
              mountPath: /usr/share/logstash/pipeline
      volumes:
        - name: config-volume
          configMap:
            name: logstash-config
        - name: config-pipeline-volume
          configMap:
            name: logstash-pipeline-config
