---
apiVersion: v1
kind: Service
metadata:
  namespace: elk
  name: logstash
spec:
  selector:
    app: logstash
  ports:
    - name: default
      port: 9600
      targetPort: default
    - name: tcp
      port: 5000
      targetPort: tcp
    - name: beats
      port: 5044
      targetPort: beats
---
apiVersion: v1
kind: Service
metadata:
  namespace: elk
  name: logstash-np
spec:
  type: NodePort
  selector:
    app: logstash
  ports:
    - name: default
      port: 9600
      targetPort: default
      nodePort: 32503
    - name: tcp
      port: 5000
      targetPort: 5000
      nodePort: 32507