---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: monitoring
  name: prometheus
  labels:
    app: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus:v2.20.1
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: "1000Mi"
              cpu: "1000m"
            requests:
              memory: "500Mi"
              cpu: "500m"
          args:
            - "--config.file=/etc/prometheus/prometheus.yml"
          ports:
            - name: default
              containerPort: 9090
          volumeMounts:
            - name: config-volume
              mountPath: /etc/prometheus
              readOnly: true
            - name: prometheus-data
              mountPath: /prometheus
              readOnly: false
      volumes:
        - name: config-volume
          configMap:
            name: prometheus-config
        - name: prometheus-data
          emptyDir: {}
