---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: kubernetes-dashboard
  name: administrator
  labels:
    app: kubernetes-dashboard  
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  namespace: kubernetes-dashboard
  name: administrator
subjects:
  - kind: ServiceAccount
    name: administrator
    namespace: kubernetes-dashboard
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: administrator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  namespace: kubernetes-dashboard
  name: administrator
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
  - nonResourceURLs: ["*"]
    verbs: ["*"]
