---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: monitoring
  name: zabbix-web
  labels:
    app: zabbix-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zabbix-web
  template:
    metadata:
      labels:
        app: zabbix-web
    spec:
      containers:
        - name: zabbix-web
          image: zabbix/zabbix-web-nginx-pgsql:alpine-5.0.2
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: "1000Mi"
              cpu: "1000m"
            requests:
              memory: "300Mi"
              cpu: "300m"
          ports:
            - name: default
              containerPort: 8080
          envFrom:
            - configMapRef:
                name: zabbix-web-config
