---
apiVersion: v1
kind: Service
metadata:
  namespace: monitoring
  name: zabbix-web
spec:
  selector:
    app: zabbix-web
  ports:
    - port: 80
      targetPort: default
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  namespace: monitoring
  name: zabbix-web-np
spec:
  type: NodePort
  selector:
    app: zabbix-web
  ports:
    - port: 80
      targetPort: default
      nodePort: 32502
      protocol: TCP
