---
apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: monitoring
  name: zabbix-pgsql-pv
  labels:
    app: zabbix-pgsql
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: ${nfs-ip}
    path: "/media/nfs/zabbix/postgresql"
    readOnly: false
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: monitoring
  name: zabbix-pgsql-pvc
  labels:
    app: zabbix-pgsql
spec:
  selector:
    matchLabels:
      app: zabbix-pgsql
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
