version: "3.7"

services:
  zabbix-web:
    image: zabbix/zabbix-web-nginx-pgsql:alpine-5.0.2
    restart: unless-stopped
    user: root:root
    ports:
      - 3002:8080
    networks:
      - traefik-public
      - zabbix-private
    environment:
      DB_SERVER_HOST: zabbix-database
      DB_SERVER_PORT: 5432
      POSTGRES_DB: zabbix
      POSTGRES_PASSWORD: db_pass
      POSTGRES_USER: postgres
      ZBX_SERVER_HOST: zabbix-server
      ZBX_SERVER_PORT: 10051
    deploy:
      replicas: 1
      labels:
        - traefik.enable=true
        - traefik.http.routers.zabbix.rule=Host(`${zabbix-host}`)
        - traefik.http.routers.zabbix.entrypoints=web
        - traefik.http.services.zabbix.loadbalancer.server.port=8080
      resources:
        limits:
          memory: 2048M
          cpus: "2"

  zabbix-server:
    image: zabbix/zabbix-server-pgsql:alpine-5.0.2
    user: root
    networks:
      - traefik-public
      - zabbix-private
    environment:
      DB_SERVER_HOST: zabbix-database
      DB_SERVER_PORT: 5432
      POSTGRES_DB: zabbix
      POSTGRES_PASSWORD: db_pass
      POSTGRES_USER: postgres
      ZBX_CACHESIZE: 1G
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 3072M
          cpus: "2"
        reservations:
          cpus: "1"
          memory: 2048M

  zabbix-database:
    image: postgres:13-alpine
    user: root
    networks:
      - zabbix-private
    environment:
      POSTGRES_DB: zabbix
      POSTGRES_PASSWORD: db_pass
    volumes:
      - type: volume
        source: zabbix-pg-data
        target: /var/lib/postgresql/data
        volume:
          nocopy: true
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 2048M
          cpus: "2"

volumes:
  zabbix-pg-data:
    driver: local
    driver_opts:
      type: nfs
      device: :/media/nfs/zabbix
      o: addr=${nfs-ip},nolock,soft,rw

networks:
  zabbix-private:
    driver: overlay
  traefik-public:
    external: true
