---
apiVersion: v1
kind: Service
metadata:
  namespace: elk
  name: apm-server
spec:
  selector:
    app: apm-server
  ports:
    - port: 8200
      targetPort: default
---
apiVersion: v1
kind: Service
metadata:
  namespace: elk
  name: apm-server-np
spec:
  type: NodePort
  selector:
    app: apm-server
  ports:
    - port: 8200
      targetPort: default
      nodePort: 32506
