---
apiVersion: v1
kind: Service
metadata:
  namespace: elk
  name: elasticsearch
spec:
  selector:
    app: elasticsearch
  ports:
    - port: 9200
      targetPort: default
---
apiVersion: v1
kind: Service
metadata:
  namespace: elk
  name: elasticsearch-np
spec:
  type: NodePort
  selector:
    app: elasticsearch
  ports:
    - name: default
      port: 9200
      targetPort: default
      nodePort: 32504
    - name: nodes
      port: 9300
      targetPort: nodes
      nodePort: 32601
