---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: monitoring
  name: zabbix-server
  labels:
    app: zabbix-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zabbix-server
  template:
    metadata:
      labels:
        app: zabbix-server
    spec:
      containers:
        - name: zabbix-server
          image: zabbix/zabbix-server-pgsql:alpine-5.0.2
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: "1000Mi"
              cpu: "1000m"
            requests:
              memory: "300Mi"
              cpu: "300m"
          ports:
            - name: default
              containerPort: 10051
          envFrom:
            - configMapRef:
                name: zabbix-server-config
