---
apiVersion: v1
kind: Service
metadata:
  namespace: monitoring
  name: zabbix-server
spec:
  selector:
    app: zabbix-server
  ports:
    - port: 80
      targetPort: default
      protocol: TCP
