---
apiVersion: v1
kind: Service
metadata:
  namespace: elk
  name: kibana
spec:
  selector:
    app: kibana
  ports:
    - port: 5601
      targetPort: default
---
apiVersion: v1
kind: Service
metadata:
  namespace: elk
  name: kibana-np
spec:
  type: NodePort
  selector:
    app: kibana
  ports:
    - port: 5601
      targetPort: default
      nodePort: 32505
