---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: monitoring
  name: grafana-config
data:
  GF_DATABASE_HOST: grafana-pgsql
  GF_DATABASE_NAME: grafana
  GF_DATABASE_USER: grafana
  GF_DATABASE_PASSWORD: grafana_password
  GF_DATABASE_TYPE: postgres
  GF_INSTALL_PLUGINS: alexanderzobnin-zabbix-app,grafana-clock-panel,briangann-gauge-panel,grafana-simple-json-datasource,grafana-piechart-panel
  GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: alexanderzobnin-zabbix-datasource
  # GF_REMOTE_CACHE_TYPE: redis
  # GF_REMOTE_CACHE_CONNSTR: addr=127.0.0.1:6379,pool_size=100,db=0,ssl=false
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: monitoring
  name: grafana-config
data:
  datasource.ini: |
    apiVersion: v1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus:9090