---
apiVersion: v1
kind: Service
metadata:
  namespace: monitoring
  name: grafana
  labels:
    app: grafana
spec:
  selector:
    app: grafana
  ports:
    - port: 3000
      targetPort: default
---
apiVersion: v1
kind: Service
metadata:
  namespace: monitoring
  name: grafana-np
  labels:
    app: grafana
spec:
  type: NodePort
  selector:
    app: grafana
  ports:
    - port: 3000
      targetPort: default
      nodePort: 32501
      protocol: TCP
