---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  namespace: elk
  name: filebeat
  labels:
    app: filebeat
spec:
  selector:
    matchLabels:
      app: filebeat
  template:
    metadata:
      labels:
        app: filebeat
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      tolerations:
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
      serviceAccountName: filebeat
      containers:
        - name: filebeat
          image: docker.elastic.co/beats/filebeat:7.9.0
          args: ["-e"]
          resources:
            limits:
              memory: 500Mi
            requests:
              cpu: 100m
              memory: 100Mi
          securityContext:
            runAsUser: 0
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: config-volume
              mountPath: /usr/share/filebeat/filebeat.yml
              readOnly: true
              subPath: filebeat.yml
            - name: data-volume
              mountPath: /usr/share/filebeat/data
            - name: logs-volume
              mountPath: /var/log/containers
              readOnly: true
            - name: containers-volume
              mountPath: /var/lib/docker/containers
              readOnly: true
      volumes:
        - name: config-volume
          configMap:
            defaultMode: 0640
            name: filebeat-config
        - name: logs-volume
          hostPath:
            path: /var/log/containers
        - name: data-volume
          hostPath:
            path: /var/lib/filebeat-data
            type: DirectoryOrCreate
        - name: containers-volume
          hostPath:
            path: /var/lib/docker/containers
