---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: maven-spring-app
  labels:
    app: maven-spring-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: maven-spring-app
  template:
    metadata:
      labels:
        app: maven-spring-app
    spec:
      containers:
        - name: maven-spring-app
          image: lucastercas/maven-spring-app:11
          imagePullPolicy: Always
          resources:
            limits:
              memory: "500Mi"
            requests:
              memory: "250Mi"
          ports:
            - name: default
              containerPort: 8080
          env:
            - name: ELASTIC_APM_SERVER_URLS
              value: http://apm-server.elk:8200
            - name: LOGSTASH_SERVER
              value: logstash.elk:5000
---
apiVersion: v1
kind: Service
metadata:
  name: maven-spring-app
  labels:
    app: maven-spring-app
spec:
  selector:
    app: maven-spring-app
  ports:
    - port: 8080
      targetPort: default
---
apiVersion: v1
kind: Service
metadata:
  name: maven-spring-app-np
  labels:
    app: maven-spring-app
spec:
  type: NodePort
  selector:
    app: maven-spring-app
  ports:
    - port: 8080
      nodePort: 32600
      targetPort: default
