---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-vue-app
  labels:
    app: node-vue-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-vue-app
  template:
    metadata:
      labels:
        app: node-vue-app
    spec:
      containers:
        - name: node-vue-app
          image: lucastercas/node-vue-app:1
          imagePullPolicy: Always
          resources:
            limits:
              memory: "500Mi"
            requests:
              memory: "250Mi"
          ports:
            - name: default
              containerPort: 80
          env:
            - name: ELASTIC_APM_SERVER_URLS
              value: http://apm-server.elk:8200
            - name: LOGSTASH_SERVER
              value: logstash.elk:5000
---
apiVersion: v1
kind: Service
metadata:
  name: node-vue-app
  labels:
    app: node-vue-app
spec:
  selector:
    app: node-vue-app
  ports:
    - port: 80
      targetPort: default
---
apiVersion: v1
kind: Service
metadata:
  name: node-vue-app-np
  labels:
    app: node-vue-app
spec:
  type: NodePort
  selector:
    app: node-vue-app
  ports:
    - port: 80
      nodePort: 32601
      targetPort: default
